version: '3'
services:
    smart: 
        image: smartplatform/pocit:testversion
        user: root
        ports:
            - "8100:3306"
            - "8081:80"
            - "9082:9081"
        volumes:
                - "/root/Fresh2Rely/Docker/deploy-app:/app"
                - "/root/Fresh2Rely/Docker/app-data:/var/lib/mysql"
        entrypoint: /bin/bash
        command:
            - /home/run.sh

